<?php
namespace backend\controllers;

use backend\models\UML;
use backend\models\Xml;
use Exception;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class XmlController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionImport()
    {
        Xml::doIt();
    }
}