<?php
namespace frontend\controllers;

use backend\models\Sitemap;
use backend\models\UML;
use Exception;
use frontend\models\Xml;
use SimpleXMLElement;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class XmlController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionImport()
    {
        Xml::parseAll();
    }
}