<?php
namespace frontend\controllers;

use backend\models\Sitemap;
use backend\models\UML;
use Exception;
use frontend\models\Xml;
use SimpleXMLElement;
use Yii;
use yii\web\Controller;

/**
 * Site controller
 */
class XmlController extends Controller
{
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionImport()
    {
        $xml = new Xml();
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $victoryFit = simplexml_load_file('https://victoryfit.ru/wp-content/uploads/market-exporter/ym-export.yml');
            $victoryFitArray = [];

            foreach($victoryFit->catalog->items->item as $offer) {
                $available = (string) $offer->attributes()->{'available'};
                $artikul = (string) $offer->vendorCode;
                $price = (int) $offer->price;

                $unixfitArray[$artikul]['price'] = $price;
                $unixfitArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('VictoryFit', $victoryFitArray, 24, false);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $wellFitness = simplexml_load_file('http://www.wellfitness.ru/system/storage/download/export.xml');
            $wellFitnessArray = [];

            foreach($wellFitness->catalog->items->item as $offer) {
                $available = (int) $offer->QUANTITY;
                $artikul = (string) trim($offer->article);
                $price = (int) $offer->price;

                $wellFitnessArray[$artikul]['price'] = $price;
                $wellFitnessArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('wellFitness', $wellFitnessArray, 9, false);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER["HTTP_USER_AGENT"]);
            curl_setopt($ch, CURLOPT_VERBOSE, 1);
            curl_setopt($ch, CURLOPT_URL, 'https://hasttings.ru/diler/login/');
            curl_setopt($ch, CURLOPT_POST, 1);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, "site_user_login=ksg&site_user_password=qwertydas123&remember_me=1&apply=Войти");
            curl_setopt($ch, CURLOPT_COOKIESESSION, true);
            curl_setopt($ch, CURLOPT_COOKIEJAR, Yii::getAlias('@www').'/cookie.txt');
            curl_exec($ch);

            curl_setopt($ch, CURLOPT_COOKIEFILE, Yii::getAlias('@www').'/cookie.txt');
            curl_setopt($ch, CURLOPT_URL, 'https://hasttings.ru/diler/fast.yml');
            $result = curl_exec($ch);

            $hasttings = simplexml_load_string($result);
            $hasttingsArray = [];

            foreach($hasttings->shop->offers->offer as $offer) {
                if ($offer->available == 'true') {
                    $available = 10;
                } else {
                    $available = 0;
                }

                $artikul = (string) $offer->marking;
                $price = (int) $offer->price;

                $hasttingsArray[$artikul]['price'] = $price;
                $hasttingsArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('hasttings', $hasttingsArray, 3, false);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $unixfit = simplexml_load_file('http://unixfit.ru/bitrix/catalog_export/catalog.php');
            $unixfitArray = [];

            foreach($unixfit->shop->offers->offer as $offer) {
                $available = (string) $offer['available'] === 'false' ? 0 : 10;
                $artikul = (string) $offer->vendorCode;
                $price = (int) $offer->price;

                $unixfitArray[$artikul]['price'] = $price;
                $unixfitArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('unixfit', $unixfitArray, 7, false);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $neotren = simplexml_load_file('https://neotren.ru/yml.php');
            $neotrenArray = [];

            foreach($neotren->shop->offers->offer as $offer) {
                $offerXml = $offer->asXml();

                if (strstr($offerXml, '<param name="status"/>')) {
                    $available = 0;
                } else {
                    preg_match('#<param name="status">([^<]+)</param>#siU', $offerXml, $match);
                    $available = $match[1];
                }

                $artikul = (string) $offer->vendorCode;
                $price = (int) $offer->price;

                $neotrenArray[$artikul]['price'] = $price;
                $neotrenArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('neotren', $neotrenArray, 5, false);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $fitnessBoutique = simplexml_load_file('https://www.fitness-boutique.ru/system/files/dealer/stock_fitness-boutique_xml.xml');
            $fitnessBoutiqueArray = [];

            foreach($fitnessBoutique->shop->offers->offer as $offer) {
                $available = (string) $offer->attributes()->{'available'};
                $artikul = (string) $offer->param;
                $price = (int) $offer->price;

                $fitnessBoutiqueArray[$artikul]['price'] = $price;
                $fitnessBoutiqueArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('fitnessBoutique', $fitnessBoutiqueArray, 8, true);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $soulfit = simplexml_load_file('http://soulfitnes.ru/wp-content/plugins/saphali-export-yml2/export.yml');
            $soulfitArray = [];

            foreach($soulfit->shop->offers->offer as $offer) {
                $available = (string) $offer->attributes()->{'available'};
                $artikul = (string) $offer->vendorCode;
                $price = (int) $offer->price;

                $soulfitArray[$artikul]['price'] = $price;
                $soulfitArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('soulfit', $soulfitArray, 4);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $stark = simplexml_load_file('http://xn----dtbgdaodln4afhyim1m.com/price/?sklad=moscow');
            $starkArray = [];

            foreach($stark->products->product as $product) {
                foreach($product->offers->offer as $offer) {
                    $available = (string) $offer->attributes()->{'available'};
                    $artikul = (string) $offer->articul;
                    $price = (int) $product->price;

                    $starkArray[$artikul]['price'] = $price;
                    $starkArray[$artikul]['available'] = $available;
                }
            }

            $xml->loadXml('stark', $starkArray, 6);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }
        ////////////////////////////////////////////////////////////////////////////////
        /*try {
            $svenson = simplexml_load_file('https://jorgen-svensson.com/ru/data.yml');
            $svensonArray = [];

            foreach($svenson->shop->offers->offer as $offer) {
                $available = (string) $offer->param;
                $artikul = (string) $offer->vendorCode;
                $price = (int) $offer->price;

                $svensonArray[$artikul]['price'] = $price;
                $svensonArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('jorgen-svensson', $svensonArray, 2);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }*/
        ////////////////////////////////////////////////////////////////////////////////
        try {
            $driada = simplexml_load_file('http://driada-sport.ru/data/files/XML_prise_s.xml');
            $driadaArray = [];

            foreach($driada->price as $offer) {
                $values = $offer->attributes();
                $available = (string) $values['Остаток'];
                $artikul = (string) $values['Артикул'];
                $price = (int) $values['Цена'];

                $driadaArray[$artikul]['price'] = $price;
                $driadaArray[$artikul]['available'] = $available;
            }

            $xml->loadXml('driada', $driadaArray, 1);
        } catch(Exception $e) {
            $xml->sendMessage("Ошибка при парсинге прайс листа KSG", $e->getMessage());
        }

        UML::doIt();
        ////////////////////////////////////////////////////////////////////////////////
        //echo '<pre>',print_r($driada->shop->offers),'</pre>';
    }
}