<?php

namespace common\models;

use Yii;
use \common\models\base\FeatureValue as BaseFeatureValue;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "feature_value".
 */
class FeatureValue extends BaseFeatureValue
{

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                # custom behaviors
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
            parent::rules(),
            [
                [['main_param'], 'integer']
            ]
        );
    }

    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(), [
            'main_param' => 'Ключевая?'
        ]); // TODO: Change the autogenerated stub
    }
}
