<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models;

use Yii;

/**
 * This is the base-model class for table "mainpage".
 *
 * @property integer $id
 * @property string $name
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_description
 * @property string $aliasModel
 */
class Mainpage extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mainpage';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['delivery_free_from'], 'integer'],
            [['seo_description', 'delivery', 'product_delivery_left', 'product_delivery_right'], 'string'],
            [['name', 'seo_title', 'seo_keywords', 'banner_image'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_description' => 'Seo Description',
            'delivery' => 'Текст доставки в корзине',
            'banner_image' => 'Баннер для товара',
            'delivery_free_from' => 'Начиная с этой цену, у товара будет бесплатная доставка',
            'product_delivery_left' => 'Доставка для товара (левая колонка)',
            'product_delivery_right' => 'Доставка для товара (правая колонка)',
        ];
    }




}
