<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "category".
 *
 * @property integer $id
 * @property string $name
 * @property string $alias
 * @property integer $type
 * @property integer $sort_order
 * @property integer $parent_id
 * @property integer $priority
 * @property string $aksses_ids
 * @property string $text_advice
 * @property string $descr
 * @property string $image_catalog
 * @property string $image_menu
 * @property string $video
 * @property string $video_header
 * @property integer $disallow_xml
 * @property string $seo_h1
 * @property string $seo_title
 * @property string $seo_keywords
 * @property string $seo_description
 * @property integer $brand_id
 * @property integer $active
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Category extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'sort' => [
                'class' => SortableGridBehavior::className(),
                'sortableAttribute' => 'sort_order'
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'type'], 'required'],
            [['type', 'sort_order', 'parent_id', 'priority', 'disallow_xml', 'brand_id', 'active'], 'integer'],
            [['aksses_ids', 'text_advice', 'descr', 'seo_description'], 'string'],
            [['name', 'alias', 'image_catalog', 'image_menu', 'video', 'video_header', 'seo_h1', 'seo_title', 'seo_keywords'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Урл',
            'type' => 'Тип категории',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'sort_order' => 'Sort Order',
            'parent_id' => 'Родительская категория',
            'priority' => 'Приоритет',
            'aksses_ids' => 'Аксессуары',
            'text_advice' => 'Текст(совет)',
            'descr' => 'Описание',
            'image_catalog' => 'Изображение в каталоге(1600x250)',
            'image_menu' => 'Изображение в меню(134x134)',
            'video' => 'id видео на youtube',
            'video_header' => 'Видео заголовок',
            'disallow_xml' => 'Запретить вывод товаров этой категории в xml?',
            'seo_h1' => 'Seo H1',
            'seo_title' => 'Seo Title',
            'seo_keywords' => 'Seo Keywords',
            'seo_description' => 'Seo Description',
            'brand_id' => 'Соответствующий бренд',
            'active' => 'Активна?',
            'filter_url' => 'Урл для фильтра',
        ];
    }




}
