<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "changer".
 *
 * @property integer $id
 * @property integer $product_id
 * @property double $old_price
 * @property double $new_price
 * @property double $percent
 * @property integer $supplier_id
 * @property integer $brand_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Changer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'changer';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'supplier_id', 'brand_id'], 'integer'],
            [['old_price', 'new_price', 'percent'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'product_id' => 'Product ID',
            'old_price' => 'Old Price',
            'new_price' => 'New Price',
            'percent' => 'Percent',
            'supplier_id' => 'Supplier ID',
            'brand_id' => 'Brand ID',
        ];
    }




}
