<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "present".
 *
 * @property integer $id
 * @property integer $other_price
 * @property integer $moscow_price
 * @property integer $lt
 * @property integer $gte
 */
abstract class Delivery extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'delivery';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [

        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['other_price', 'moscow_price', 'lt', 'gte'], 'integer'],
            [['other_price', 'moscow_price', 'lt', 'gte'], 'required'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'other_price' => 'Цена для России',
            'moscow_price' => 'Цена для Москвы',
            'lt' => 'Меньше( < )',
            'gte' => 'Больше ( >= )',
        ];
    }




}
