<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "feature".
 *
 * @property integer $id
 * @property string $header
 * @property integer $category_id
 * @property integer $product_id
 * @property integer $sort_order
 * @property string $aliasModel
 */
abstract class Feature extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'feature';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category_id', 'product_id', 'sort_order'], 'integer'],
            [['header'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'header' => 'Заголовок',
            'category_id' => 'Category ID',
            'product_id' => 'Product ID',
            'sort_order' => 'Sort Order',
        ];
    }




}
