<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "feature_value".
 *
 * @property integer $id
 * @property string $name
 * @property string $value
 * @property integer $sort_order
 * @property integer $feature_id
 * @property string $aliasModel
 */
abstract class FeatureValue extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'feature_value';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sort_order', 'feature_id'], 'integer'],
            [['name', 'value'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'value' => 'Значение',
            'sort_order' => 'Sort Order',
            'feature_id' => 'Feature ID',
        ];
    }




}
