<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "image".
 *
 * @property integer $id
 * @property string $image
 * @property string $text
 * @property integer $product_id
 * @property integer $sort_order
 * @property string $aliasModel
 */
abstract class Image extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'image';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['image', 'text'], 'required'],
            [['text'], 'string'],
            [['product_id', 'sort_order'], 'integer'],
            [['image'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'image' => 'Изображение(770x553)',
            'text' => 'Текст',
            'product_id' => 'Product ID',
            'sort_order' => 'Sort Order',
        ];
    }




}
