<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "mainslider".
 *
 * @property integer $id
 * @property string $header
 * @property string $image
 * @property string $text
 * @property string $link
 * @property integer $sort_order
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Mainslider extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'mainslider';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'sort' => [
                'class' => SortableGridBehavior::className(),
                'sortableAttribute' => 'sort_order'
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['header', 'image', 'text'], 'required'],
            [['text'], 'string'],
            [['sort_order'], 'integer'],
            [['header', 'image', 'link'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'header' => 'Заголовок',
            'image' => 'Изображение(1942x438)',
            'text' => 'Текст',
            'link' => 'Ссылка',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'sort_order' => 'Sort Order',
        ];
    }




}
