<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "order".
 *
 * @property integer $id
 * @property string $delivery
 * @property string $payments
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $shipaddress
 * @property string $comment
 * @property string $products
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 * @property string $paid
 */
abstract class Order extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['delivery', 'payments', 'name', 'phone', 'email', 'total_cost'], 'required'],
            [['products'], 'safe'],
            [['paid'], 'integer'],
            [['delivery', 'payments', 'name', 'phone', 'email', 'shipaddress', 'comment', 'promocode', 'total_cost'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'delivery' => 'Доставка',
            'payments' => 'Оплата',
            'name' => 'Имя клиента',
            'phone' => 'Телефон клиента',
            'email' => 'Email клиента',
            'shipaddress' => 'Адрес доставки',
            'comment' => 'Комментарий к заказу',
            'products' => 'Товары',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата изменения',
            'promocode' => 'Промокод',
            'total_cost' => 'Общая сумма заказа',
        ];
    }




}
