<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "order".
 *
 * @property integer $id
 * @property string $payment
 * @property string $name
 * @property string $phone
 * @property string $email
 * @property string $address
 * @property string $comm
 * @property string $products
 * @property double $total_cost
 * @property integer $paid
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $aliasModel
 */
abstract class Order extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'order';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['payment', 'name', 'phone', 'email', 'total_cost', 'status'], 'required'],
            [['products'], 'string'],
            [['total_cost'], 'number'],
            [['paid', 'status'], 'integer'],
            [['payment', 'name', 'phone', 'email', 'address', 'comm'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'payment' => 'Оплата',
            'name' => 'Имя клиента',
            'phone' => 'Телефон клиента',
            'email' => 'Email клиента',
            'address' => 'Адрес',
            'comm' => 'Комментарий к заказу',
            'products' => 'Товары',
            'total_cost' => 'Total Cost',
            'created_at' => 'Дата создания',
            'updated_at' => 'Дата изменения',
            'paid' => 'Оплачено?',
            'status' => 'Статус',
        ];
    }




}
