<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "product_has_filter_feature_value".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $filter_feature_value_id
 * @property string $aliasModel
 */
abstract class ProductHasFilterFeatureValue extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_has_filter_feature_value';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'filter_feature_value_id'], 'required'],
            [['product_id', 'filter_feature_value_id'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'filter_feature_value_id' => 'Filter Feature Value ID',
        ];
    }




}
