<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "product_param".
 *
 * @property integer $id
 * @property string $artikul
 * @property integer $available
 * @property string $params
 * @property integer $image_number
 * @property integer $product_id
 * @property integer $sort_order
 * @property string $aliasModel
 */
abstract class ProductParam extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_param';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['artikul', 'available', 'params', 'image_number'], 'required'],
            [['available', 'image_number', 'product_id', 'sort_order'], 'integer'],
            [['params'], 'string'],
            [['artikul'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'artikul' => 'Артикул',
            'available' => 'Наличие',
            'params' => 'Параметры',
            'image_number' => 'Номер изображения',
            'product_id' => 'Product ID',
            'sort_order' => 'Sort Order',
        ];
    }




}
