<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "product_review".
 *
 * @property integer $id
 * @property string $name
 * @property string $text
 * @property integer $date
 * @property integer $active
 * @property integer $product_id
 * @property integer $sort_order
 * @property string $aliasModel
 */
abstract class ProductReview extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_review';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'text', 'date', 'active', 'product_id'], 'required'],
            [['text'], 'string'],
            [['date', 'active', 'product_id', 'sort_order'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'text' => 'Текст',
            'date' => 'Дата',
            'active' => 'Активен?',
            'product_id' => 'Product ID',
            'sort_order' => 'Sort Order',
        ];
    }




}
