<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use himiklab\sortablegrid\SortableGridBehavior;

/**
 * This is the base-model class for table "product_has_category".
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $category_id
 * @property integer $sort_order
 * @property string $aliasModel
 */
abstract class ProductHasCategory extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_has_category';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['product_id', 'category_id'], 'required'],
            [['product_id', 'category_id', 'sort_order'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'category_id' => 'Category ID',
            'sort_order' => 'Sort Order',
        ];
    }




}
