<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "step".
 *
 * @property integer $id
 * @property integer $survey_id
 * @property string $name
 * @property string $text
 * @property string $icon
 * @property string $options
 * @property integer $sort_order
 * @property string $inner_header
 * @property string $inner_text
 * @property integer $category_id
 * @property string $aliasModel
 */
abstract class Step extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'step';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['survey_id', 'sort_order', 'category_id'], 'integer'],
            [['text', 'icon', 'options', 'inner_header', 'inner_text'], 'string'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'survey_id' => 'Survey ID',
            'name' => 'Name',
            'text' => 'Text',
            'icon' => 'Icon',
            'options' => 'Options',
            'sort_order' => 'Sort Order',
            'inner_header' => 'Inner Header',
            'inner_text' => 'Inner Text',
            'category_id' => 'Category ID',
        ];
    }




}
